FROM --platform=armhf alpine:3.9

ENV TZ="America/Denver" \
    LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8" \
    LANGUAGE="en_US.UTF-8"

COPY qemu-arm-static /usr/bin

RUN apk add --no-cache \
    shadow \
    tzdata
